### ISSUE TITLE
ModuleNotFoundError: No module named 'report'

### ISSUE THREAD

**Issue by testwill** [chaitin/veinmind-tools#109]
**Bug 具体描述**
Traceback (most recent call last):
  File "scan.py", line 14, in <module>
    from report import *
ModuleNotFoundError: No module named 'report'

**复现步骤**
1. 进入veinmind-backdoor
2. 执行 pip install -r requirements.txt 成功
3.  python3 scan.py scan-images 192.168.1.94:443/library/av:0.5  报错
Traceback (most recent call last):
  File "scan.py", line 14, in <module>
    from report import *
ModuleNotFoundError: No module named 'report'

**相关截图**

**环境(空项可以不填)**
 - Docker 版本: 
 - libveinmind 版本:veinmind==1.1.0
 - 问脉镜像版本:
 - 代码版本: master

**补充说明**

**Comment by d1nfinite** [comment]
在项目目录下，执行
```
cp -r ./veinmind-common ./plugins/python/veinmind-backdoor && rm -rf ./plugins/python/veinmind-backdoor/veinmind-common/go
cd ./plugins/python/veinmind-backdoor
```

**Comment by testwill** [comment]
好的，谢谢
