### ISSUE TITLE
适配 harbor 镜像扫描

### ISSUE THREAD

**Issue by testwill** [chaitin/veinmind-tools#121]
这个是直接作为插件安装到harbor中吗？类似于trivy吗？

**Comment by d1nfinite** [comment]
目前 harbor 插件的适配工作仍在开发中，预计下个月可以用上

**Comment by testwill** [comment]
好的

**Comment by testwill** [comment]
扫描结果能在harbor仓库中展示吗，审查服务中

**Comment by huzai9527** [comment]
所有报告都会展示在harbor中

**Comment by testwill** [comment]
这个针对的是什么harbor版本，看官网它是默认逐步支持相关检查

**Comment by d1nfinite** [comment]
目前已支持 `harbor` 的仓库镜像扫描，具体使用可以参考文档 https://veinmind.chaitin.com/docs/mode/scan-registry/#%E4%BD%BF%E7%94%A8%E9%97%AE%E8%84%89-runner-%E6%89%AB%E6%8F%8F%E8%BF%9C%E7%A8%8B%E4%BB%93%E5%BA%93%E9%95%9C%E5%83%8F

**Comment by testwill** [comment]
你们这个是从仓库拉取镜像下来然后去扫描的，我刚开始以为你们支持harbor是使用harbor提供的api进行注册，然后可以将这些后门、木马病毒可以在harbor上面直接展示。不过这样会有局限
