### ISSUE TITLE
sys.path 的路径不对问题

### ISSUE THREAD

**Issue by 0cat-r** [chaitin/veinmind-tools#141]
![5d749a1789816fe06c6cf1e9fd4ddeb](https://user-images.githubusercontent.com/49912303/197674540-ad312e97-05bb-4773-a79e-5833d7696c20.jpg)
![db3e5190b1e51dc1ace1811a5374617](https://user-images.githubusercontent.com/49912303/197674549-8ea03108-7ec3-41ac-ac64-37dfc68a3f78.jpg)
../veinmind-common/python/service 跳一层应该是不够的

本地测试
![221ff2c9e40198ed48f71e5cd5a86d5](https://user-images.githubusercontent.com/49912303/197674605-710b359f-5f99-425c-96e2-63ab418c5fe7.jpg)

**Comment by DVKunion** [comment]
已去除sys方式import，替换为veinmin-common

**Comment by 0cat-r** [comment]
N I C E
