### ISSUE TITLE
这么编译veinmind-tools的源文件？

### ISSUE THREAD

**Issue by su9su** [chaitin/veinmind-tools#16]
debian下载了veinmind-tools的源文件要怎么编译呀？

**Comment by d1nfinite** [comment]
以 veinmind-malicious 为例， 确保 `Golang` 版本大于 1.16 的前提下， 在 veinmind-malicious 文件夹中执行 `CGO_ENABLED=1 go build -o veinmind-malicious ./cmd/scan/cli.go`

**Comment by su9su** [comment]
![F`AZ}~CXD{@(VL2{QWM $F1](https://user-images.githubusercontent.com/90330366/157586141-cbf59b2d-e844-4383-a373-7c776ec2ccb0.png)
 #我按照命令执行了然后我该怎么做呢？

**Comment by su9su** [comment]
> 以 veinmind-malicious 为例， 确保 `Golang` 版本大于 1.16 的前提下， 在 veinmind-malicious 文件夹中执行 `CGO_ENABLED=1 go build -o veinmind-malicious ./cmd/scan/cli.go`
![F`AZ}~CXD{@(VL2{QWM $F1](https://user-images.githubusercontent.com/90330366/157586433-6a4e5315-2fba-4111-9398-6c21fd9d89e3.png)
我按命令进行编译了，然后我该怎么做呢？

**Comment by aegistudio** [comment]
看起来编译没有成功，国内的话在编译前可能需要设置一下 go 代理，譬如

```export GOPROXY=https://goproxy.io```

**Comment by su9su** [comment]
问题解决了
