### ISSUE TITLE
Could not find a version that satisfies the requirement click==8.03

### ISSUE THREAD

**Issue by su9su** [chaitin/veinmind-tools#17]
![image](https://user-images.githubusercontent.com/90330366/157606589-a4b02e14-1cff-447d-b769-9051a36920ca.png)
我在使用 pip install -r requirements.txt 时出现以上问题，我需要怎么解决呢？

**Comment by d1nfinite** [comment]
换一下 `pip` 的源试试， 比如 `pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple`

**Comment by su9su** [comment]
> 

![image](https://user-images.githubusercontent.com/90330366/157607803-a0c8d773-454a-466d-9906-5a7a94c84ea8.png)
换了还是不行

**Comment by d1nfinite** [comment]
是 `pip3` 吗

**Comment by su9su** [comment]
是python2.7.16

**Comment by d1nfinite** [comment]
问脉底下的 `python` 工具都是基于 `python3.x` 进行开发的，这边需要你安装一下 `python3`

**Comment by su9su** [comment]
> 问脉底下的 `python` 工具都是基于 `python3.x` 进行开发的，这边需要你安装一下 `python3`

使用pip3成功了
