### ISSUE TITLE
GitHub Actions运行错误

### ISSUE THREAD

**Issue by jesse-zhangh** [chaitin/veinmind-tools#181]
Github Actions运行错误
`    - name: Run veinmind-tools to scan image
      uses: chaitin/veinmind-action@main
      with:
        scan-action: scan-host
        image-ref: '${{ env.ECR_REGISTRY }}/${{ env.APP_NAME }}:latest-release'
`

![Snipaste_2023-01-31_12-40-23](https://user-images.githubusercontent.com/87465352/215667765-12271fed-f653-4ea2-8cd0-e056c80a0f6a.png)

**Comment by d1nfinite** [comment]
我们新版本修改了命令行的调用方式，action 还没同步，现在正在改

**Comment by d1nfinite** [comment]
fix: https://github.com/chaitin/veinmind-action/releases/tag/v1.0.5
