### ISSUE TITLE
make plugin LANG=go NAME=test PUB=no

### ISSUE THREAD

**Issue by testwill** [chaitin/veinmind-tools#207]
**Bug 具体描述**
# make plugin.init Language=go Name=test Pub=no
make: *** No rule to make target 'plugin.init'.  Stop.

**补充说明**
没有同步修改，makefile中使用的LANG、NAME、PUB参数

**Comment by DVKunion** [comment]
这里更新了一下，现在的语法是：`make plugin Language=go Name=test Pub=no`，init有些冗余。

除此之外，可以执行`make help`进行查看。

最新文档：https://veinmind.chaitin.com/docs/pages/plugins/init/

**Comment by testwill** [comment]
好的
