### ISSUE TITLE
Readme教程报错：overlay2/imagedb/content: no such file or directory

### ISSUE THREAD

**Issue by wangdawai** [chaitin/veinmind-tools#209]
按照Readme文档无法扫描，报错如下：
Error: list image dir: open /host/var/lib/docker/image/overlay2/imagedb/content: no such file or directory

docker信息如下：
![image](https://user-images.githubusercontent.com/46709275/223679048-ccef9ffe-403c-4ca6-9e73-dea01703069c.png)

操作系统：Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core

**Comment by d1nfinite** [comment]
docker info 完整信息看一下

**Comment by wangdawai** [comment]
![image](https://user-images.githubusercontent.com/46709275/223985151-c1234f40-fda2-4fb5-8ab3-129c3b06840f.png)
![image](https://user-images.githubusercontent.com/46709275/223985403-c376aac0-8946-483d-a851-638df67ffdd9.png)


> docker info 完整信息看一下

**Comment by d1nfinite** [comment]
devicemapper 的文件驱动暂时还不支持，可以给我们提需求
