### ISSUE TITLE
Make all编译失败，没有错误提示

### ISSUE THREAD

**Issue by wangdawai** [chaitin/veinmind-tools#211]
如图，编译失败后没有任何错误提示：
![image](https://user-images.githubusercontent.com/46709275/224886934-6a4d1cf4-b918-4fdf-905e-b8f8387ac47e.png)

go 版本是1.20
环境是centos7

请问如何解决？

**Comment by DVKunion** [comment]
看上去你没有安装libveinmind，make脚本内的`make install`目前仅支持了ubuntu的libveinmind快捷安装。
可以参考 https://github.com/chaitin/libveinmind 执行一下命令安装libveinmind
```
sudo cat > /etc/yum.repos.d/libveinmind.repo << ==EOF==
[libveinmind]
name=libVeinMind SDK yum repository
baseurl=https://download.veinmind.tech/libveinmind/yum/
enabled=1
gpgcheck=0
==EOF==
sudo yum install libveinmind-devel
```

**Comment by wangdawai** [comment]
> 看上去你没有安装libveinmind，make脚本内的`make install`目前仅支持了ubuntu的libveinmind快捷安装。 可以参考 https://github.com/chaitin/libveinmind 执行一下命令安装libveinmind
> 
> ```
> sudo cat > /etc/yum.repos.d/libveinmind.repo << ==EOF==
> [libveinmind]
> name=libVeinMind SDK yum repository
> baseurl=https://download.veinmind.tech/libveinmind/yum/
> enabled=1
> gpgcheck=0
> ==EOF==
> sudo yum install libveinmind-devel
> ```

![image](https://user-images.githubusercontent.com/46709275/224915579-8d17c7ab-9553-4b66-9e75-1438c1bc504a.png)
已经按照教程安装完成

**Comment by DVKunion** [comment]
看一下

> > 看上去你没有安装libveinmind，make脚本内的`make install`目前仅支持了ubuntu的libveinmind快捷安装。 可以参考 https://github.com/chaitin/libveinmind 执行一下命令安装libveinmind
> > ```
> > sudo cat > /etc/yum.repos.d/libveinmind.repo << ==EOF==
> > [libveinmind]
> > name=libVeinMind SDK yum repository
> > baseurl=https://download.veinmind.tech/libveinmind/yum/
> > enabled=1
> > gpgcheck=0
> > ==EOF==
> > sudo yum install libveinmind-devel
> > ```
> 
> ![image](https://user-images.githubusercontent.com/46709275/224915579-8d17c7ab-9553-4b66-9e75-1438c1bc504a.png) 已经按照教程安装完成

看一下`go env`中的`CGO_ENABLED`是否开启：
`go env |grep CGO_ENANLED`
如果未开启使用：
`go env -w CGO_ENANLED=1` 开启 `CGO_ENANLED`
