### ISSUE TITLE
无法运行，提示：Error: probe docker rootfs: stat /host/var/lib/docker: no such file or directory

### ISSUE THREAD

**Issue by wangdawai** [chaitin/veinmind-tools#212]
按照教程，下载run.sh，然后 ./run.sh scan image dockerd:nginx:latest
Error: probe docker rootfs: stat /host/var/lib/docker: no such file or directory

/var/lib/docker 目录是存在的，只不过是软连接
![image](https://user-images.githubusercontent.com/46709275/225282824-1151a876-ea39-41c2-bd58-3b6d9add0ac3.png)

**Comment by d1nfinite** [comment]
新版本针对这种情况做了一定的修复，会尝试解析 `/data2/docker` 这个路径，可以用新版本试试

**Comment by wangdawai** [comment]
> 新版本针对这种情况做了一定的修复，会尝试解析 `/data2/docker` 这个路径，可以用新版本试试

docker 镜像没改吧？我按照readme里的方法运行run.sh，还是一样的错误。

**Comment by d1nfinite** [comment]
需要更新一下镜像，版本是 v2.1.0

**Comment by sevck** [comment]
原来的参数  --docker-data-root 不支持了吗？

**Comment by sevck** [comment]
![image](https://github.com/chaitin/veinmind-tools/assets/11308052/bfa3f805-551f-47c3-98c2-753040f9b752)

**Comment by sevck** [comment]
![image](https://github.com/chaitin/veinmind-tools/assets/11308052/05f279b6-1608-45fd-b88d-3fc0b8062dac)

**Comment by DVKunion** [comment]
这个问题应该修复了，请确认一下你使用的镜像是不是最新版本。(registry.veinmind.tech镜像同步暂时有些问题，以dockerhub镜像为主）。 @sevck
