### ISSUE TITLE
# sh ../scripts/build/build_veinmind_weakpass_amd64.sh 

### ISSUE THREAD

**Issue by testwill** [chaitin/veinmind-tools#24]
named files must be .go files: ./artifacts/-/veinmind-weakpass__
这个问题要怎么解决下，之前的版本还是可以执行的

**Comment by d1nfinite** [comment]
脚本里面的环境变量设置了吗

**Comment by testwill** [comment]
go mod tidy
mkdir -p ./artifacts/${CI_GOOS}-${CI_GOARCH}
export CGO_ENABLED=1 GOOS="$CI_GOOS" GOARCH="$CI_GOARCH" TAGS="$TAGS"
go build -a -tags ${TAGS} -o ./artifacts/${CI_GOOS}-${CI_GOARCH}/veinmind-weakpass_${CI_GOOS}_${CI_GOARCH} ./cmd/cli.go

这几个环境变量都要设置吗？要设置成什么样？能提供一个例子吗？

**Comment by d1nfinite** [comment]
```
export CI_GOOS=linux
export CI_GOARCH=amd64
export TAGS=community,dynamic
```

**Comment by testwill** [comment]
好了，谢谢
