### ISSUE TITLE
不能生成Json格式的结果

### ISSUE THREAD

**Issue by James-ci-git** [chaitin/veinmind-tools#255]
**Bug 具体描述**
  veinmind-tools 不能更改检测果内容的格式
**复现步骤**
1. ./veinmind-run.sh scan image a2127c821068 -o json
2. veinmind-run.sh 中的内容为：'#!/bin/bash

docker container run --rm -v /:/host -v `pwd`:/tool/resource -v /var/run/docker.sock:/var/run/docker.sock registry.veinmind.tech/veinmind/veinmind-runner $*'

**相关截图**
![json](https://github.com/chaitin/veinmind-tools/assets/42514273/bfaa083b-3fc1-4489-9cad-8a7a008d49b4)

**环境**
 - Docker 版本:  24.0.2
 - libveinmind 版本:  libveinmind-devel-1.9.21-1.x86_64
 - 问脉镜像版本:latest
 - 代码版本:

**Comment by DVKunion** [comment]
参数已变更，请尝试使用 `--format=json`，将在本地的目录生成对应的`result.json`对应文档会马上更新。

**Comment by James-ci-git** [comment]
多谢，问题已经解决。另外咱们这个veinmind-tools里面还有不少地方的文档存在错误希望能都更新一下。
