### ISSUE TITLE
可以想办法集成到harbor 里用  这个用的比较多 

### ISSUE THREAD

**Issue by BruceChinese** [chaitin/veinmind-tools#26]

**Comment by d1nfinite** [comment]
仓库扫描的功能即将上线，上线后，后面会计划支持`harbor`的仓库扫描

**Comment by d1nfinite** [comment]
@BruceChinese  目前已支持符合 [registry http api v2](https://docs.docker.com/registry/spec/api/) 标准的仓库镜像扫描，具体使用可查阅 https://github.com/chaitin/veinmind-tools/tree/master/veinmind-runner
