### ISSUE TITLE
导出报告

### ISSUE THREAD

**Issue by keven1z** [chaitin/veinmind-tools#267]
Available Commands:
  analyze     Analyze Veinmind Report With OpenAI.
  authz       Authz as docker plugin
  completion  Generate the autocompletion script for the specified shell
  generate    Generate relevant information
  help        Help about any command
  list        List relevant information
  scan        Scan cloud native objects security, include image/container/iac

Flags:
  -e, --exit-code int   exit-code when veinmind-runner find security issues
  -g, --glob string     specifies the pattern of plugin file to find
  -h, --help            help for veinmind-runner
  -o, --output string   output filepath of report
      --threads int     threads for scan action (default 5)

flag -o好像没用，只能在本地导出report.json，可以自定义导出报告路径么？

**Comment by DVKunion** [comment]
目前暂不支持自定义导出的报告文件；下一个版本可能考虑开放出来。

**Comment by keven1z** [comment]
好的
