### ISSUE TITLE
请教一下，iac扫描结果中的描述（desc）和修改方案（solution）的来源库是什么？存在哪里？

### ISSUE THREAD

**Issue by fwfan** [chaitin/veinmind-tools#269]
![image](https://github.com/chaitin/veinmind-tools/assets/44999284/a7f0ea84-d933-4eed-ac78-9d867c53c9f0)
 

如题，是否有公共开源可查看的资源库？

**Comment by DVKunion** [comment]
https://github.com/chaitin/veinmind-tools/blob/master/plugins/go/veinmind-iac/rules/common/docker.rego 简要的记录了规则的描述和解决方案。
