### ISSUE TITLE
# sh ../scripts/build/build_veinmind_weakpass_amd64.sh 报错

### ISSUE THREAD

**Issue by testwill** [chaitin/veinmind-tools#79]
错误如下：
# github.com/chaitin/libveinmind/go/pkg/binding
/root/GOPATH/pkg/mod/github.com/chaitin/libveinmind@v1.0.7/go/pkg/binding/functions.go:273:3: not enough arguments in call to (_Cfunc_veinmind_DockerNew)
        have (*_Ctype_ulong)
        want (*_Ctype_ulong, _Ctype_ulong)
/root/GOPATH/pkg/mod/github.com/chaitin/libveinmind@v1.0.7/go/pkg/binding/functions.go:314:3: not enough arguments in call to (_Cfunc_veinmind_ContainerdNew)
        have (*_Ctype_ulong)
        want (*_Ctype_ulong, _Ctype_ulong)

系统：Ubuntu 20.04.4 LTS \n \l

**Comment by d1nfinite** [comment]
更新一下 libveinmind 的版本， veinmind-weakpass 里面的 libveinmind 是 v1.1.1

**Comment by d1nfinite** [comment]
go get -u github.com/chaitin/libveinmind

**Comment by testwill** [comment]
好的，谢谢

**Comment by testwill** [comment]
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
编译veinmind-malicious 报错了

**Comment by d1nfinite** [comment]
> error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. 编译veinmind-malicious 报错了

这个报错看起来和问脉没有关系

**Comment by testwill** [comment]
嗯，我自己解决了
